[tool.poetry]
name = "pt750"
version = "0.1.0"
description = "label printing tools for brother PT-P750W label maker"
authors = ["rpedde <ron@pedde.com>"]
license = "GPL3"

[tool.poetry.dependencies]
python = "^3.9"
Pillow = "^9.1.0"
treepoem = "^3.14.0"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
flake8 = "^4.0.1"
flake8-import-order = "^0.18.1"
pytest = "^7.1.1"
mypy = "^0.942"

[tool.poetry.scripts]
makelabel = "pt750.main:main"

[[tool.mypy.overrides]]
module = "PIL"
ignore_missing_imports = true


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
